spring.datasource.url=jdbc:mysql://localhost:3306/mrrs_db
spring.datasource.username=root
spring.datasource.password=Burmanthukha992006!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
